---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger-system
spec:
  releaseName: flagger
  chart:
    spec:
      sourceRef:
        kind: OCIRepository
        name: flagger
      chart: flagger
      version: 1.42.0
  interval: 12h
  install: # override existing Flagger CRDs
    crds: CreateReplace
  upgrade: # update Flagger CRDs
    crds: CreateReplace
  values:
    prometheus:
      install: true
    meshProvider: gatewayapi:v1
